'use strict';function y(h,a,b,d){h.v.hc(h.Ta,a,b,d,void 0)}function C(h,a,b,d){h.v.pa?y(h,a,b,d):h.v.Xe()._OnMessageFromDOM({type:"event",component:h.Ta,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function D(h,a,b){h.v.B(h.Ta,a,b)}function E(h,a){for(const [b,d]of a)D(h,b,d)}function F(h){h.Kb||(h.v.Ie(h.Sd),h.Kb=!0)}window.nb=class{constructor(h,a){this.v=h;this.Ta=a;this.Kb=!1;this.Sd=()=>this.Ba()}Xc(){}Ba(){}};function H(h){-1!==h.Ma&&(self.clearTimeout(h.Ma),h.Ma=-1)}
window.ze=class{constructor(h,a){this.Ec=h;this.kg=a;this.Ma=-1;this.Lb=-Infinity;this.Td=()=>{this.Ma=-1;this.Lb=Date.now();this.Ya=!0;this.Ec();this.Ya=!1};this.Cd=this.Ya=!1}c(){H(this);this.Td=this.Ec=null}};"use strict";function I(h,a){D(h,"get-element",b=>{const d=h.ca.get(b.elementId);return a(d,b)})}
window.Dg=class extends self.nb{constructor(h,a){super(h,a);this.ca=new Map;this.Dc=!0;E(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Dc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Dc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Dc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ca.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);I(this,b=>b)}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(u){if(u.ug){const f=document.createElement("script");f.async=!1;f.textContent=u.xg;document.head.appendChild(f)}else return new Promise((f,k)=>{const c=document.createElement("script");c.onload=f;c.onerror=k;c.async=!1;c.src=u;document.head.appendChild(c)})}let b=new Audio;const d={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function g(u){u=await n(u);return(new TextDecoder("utf-8")).decode(u)}function n(u){return new Promise((f,k)=>{const c=new FileReader;c.onload=e=>f(e.target.result);c.onerror=e=>k(e);c.readAsArrayBuffer(u)})}const q=[];let t=0;window.RealFile=window.File;const w=
[],A=new Map,v=new Map;let x=0;const B=[];self.Jg=function(u){if("function"!==typeof u)throw Error("runOnStartup called without a function");B.push(u)};const z=new Set(["cordova","playable-ad","instant-games"]);window.tb=class u{constructor(f){this.pa=f.zg;this.na=null;this.J="";this.Tb=f.wg;this.mb={};this.ma=this.Fa=this.lb=null;this.Ib=[];this.$a=this.I=this.Ka=null;this.Ja=-1;this.pg=()=>this.wf();this.Ia=[];this.P=f.Ud;!this.pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||
(this.pa=!1);z.has(this.P)&&this.pa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.pa=!1);this.Nb=this.ha=null;"html5"!==this.P&&"playable-ad"!==this.P||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>
this.ef(k));this.B("runtime","create-job-worker",()=>this.ff());"cordova"===this.P?document.addEventListener("deviceready",()=>this.pd(f)):this.pd(f)}c(){this.nc();this.na&&(this.na=this.na.onmessage=null);this.lb&&(this.lb.terminate(),this.lb=null);this.Fa&&(this.Fa.c(),this.Fa=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}dd(){return h&&"cordova"===this.P}rb(){return h&&z.has(this.P)||navigator.standalone}async pd(f){"preview"===this.P&&(this.ma=document.createElement("div"),
this.ma.className="previewLoadingMessage",this.ma.textContent=f.Hg,document.body.appendChild(this.ma));if("playable-ad"===this.P){this.ha=self.c3_base64files;this.Nb={};await this.Ne();for(let c=0,e=f.Na.length;c<e;++c){var k=f.Na[c].toLowerCase();this.Nb.hasOwnProperty(k)?f.Na[c]={ug:!0,xg:this.Nb[k]}:this.ha.hasOwnProperty(k)&&(f.Na[c]=URL.createObjectURL(this.ha[k]))}}f.rg?this.J=f.rg:(k=location.origin,this.J=("null"===k?"file:///":k)+location.pathname,k=this.J.lastIndexOf("/"),-1!==k&&(this.J=
this.J.substr(0,k+1)));if(f.Bg)for(const [c,e]of Object.entries(f.Bg))this.mb[c]=URL.createObjectURL(e);k=new MessageChannel;this.na=k.port1;this.na.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.sf(c));this.$a=new self.ve(this);await J(this.$a);this.ed();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.pa?await this.Ze(f,k.port2):
await this.Ye(f,k.port2)}qc(f){return this.mb.hasOwnProperty(f)?this.mb[f]:f.endsWith("/workermain.js")&&this.mb.hasOwnProperty("workermain.js")?this.mb["workermain.js"]:"playable-ad"===this.P&&this.ha.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this.ha[f.toLowerCase()]):f}async $b(f,k,c){if(f.startsWith("blob:"))return new Worker(f,c);if(this.dd()&&"file:"===location.protocol)return f=await this.Zb(this.Tb+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),c);
f=new URL(f,k);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),c)}return new Worker(f,c)}ua(){return Math.max(window.innerWidth,1)}ta(){return Math.max(window.innerHeight,1)}ed(){if(this.rb()){const f=document.documentElement.style,k=document.body.style,c=window.innerWidth<window.innerHeight,e=c?window.screen.width:window.screen.height;k.height=f.height=(c?window.screen.height:window.screen.width)+
"px";k.width=f.width=e+"px"}}od(f){var k=this.$a;return{baseUrl:this.J,windowInnerWidth:this.ua(),windowInnerHeight:this.ta(),devicePixelRatio:window.devicePixelRatio,isFullscreen:u.fc(),projectData:f.Ig,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.Ud,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Gg,jobScheduler:{inputPort:k.Kc,outputPort:k.Rc,maxNumWorkers:k.mg},supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.Tb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Tb+"opus.wasm.wasm",isiOSCordova:this.dd(),isiOSWebView:this.rb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ze(f,k){var c=this.qc(f.Ag);this.lb=await this.$b(c,this.J,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";c=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;this.lb.postMessage(Object.assign(this.od(f),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:c,workerDependencyScripts:f.Wc||[],engineScripts:f.Na,projectScripts:window.Fg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,c,...K(this.$a)]);this.Ib=w.map(e=>new e(this));this.nd();self.c3_callFunction=(e,l)=>this.Ka.$e(e,l);"preview"===this.P&&(self.goToLastErrorScript=()=>this.hc("runtime","go-to-last-error-script"))}async Ye(f,k){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;
this.Ib=w.map(e=>new e(this));this.nd();const c=f.Na.map(e=>"string"===typeof e?(new URL(e,this.J)).toString():e);Array.isArray(f.Wc)&&c.unshift(...f.Wc);await Promise.all(c.map(e=>a(e)));if(f.Vd&&0<f.Vd.length){const e=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.Vd.map(l=>a(l[1]))),Object.values(e).some(l=>!l)){self.setTimeout(()=>this.xd(e),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this.xd(e),100);return}}"preview"===this.P&&
"object"!==typeof self.Cg.Eg?(this.Cb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.od(f),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:B}),this.rd(),this.Fa=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.Fa,f))}xd(f){this.Cb();f=`Failed to load project script '${Object.entries(f).filter(k=>
!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}rd(){this.Cb()}Cb(){this.ma&&(this.ma.parentElement.removeChild(this.ma),this.ma=null)}async ff(){const f=await L(this.$a);return{outputPort:f,transferables:[f]}}Xe(){if(this.pa)throw Error("not available in worker mode");return this.Fa}hc(f,k,c,e,l){this.na.postMessage({type:"event",component:f,handler:k,dispatchOpts:e||null,data:c,responseId:null},l)}fd(f,k,c,e,l){const m=x++,p=new Promise((r,
G)=>{v.set(m,{resolve:r,reject:G})});this.na.postMessage({type:"event",component:f,handler:k,dispatchOpts:e||null,data:c,responseId:m},l);return p}["_OnMessageFromRuntime"](f){const k=f.type;if("event"===k)return this.lf(f);if("result"===k)this.zf(f);else if("runtime-ready"===k)this.Af();else if("alert-error"===k)this.Cb(),alert(f.message);else if("creating-runtime"===k)this.rd();else throw Error(`unknown message '${k}'`);}lf(f){const k=f.component,c=f.handler,e=f.data,l=f.responseId;if(f=A.get(k))if(f=
f.get(c)){var m=null;try{m=f(e)}catch(p){console.error(`Exception in '${k}' handler '${c}':`,p);null!==l&&this.Ab(l,!1,""+p);return}if(null===l)return m;m&&m.then?m.then(p=>this.Ab(l,!0,p)).catch(p=>{console.error(`Rejection from '${k}' handler '${c}':`,p);this.Ab(l,!1,""+p)}):this.Ab(l,!0,m)}else console.warn(`[DOM] No handler '${c}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ab(f,k,c){let e;c&&c.transferables&&(e=c.transferables);this.na.postMessage({type:"result",
responseId:f,isOk:k,result:c},e)}zf(f){const k=f.responseId,c=f.isOk;f=f.result;const e=v.get(k);c?e.resolve(f):e.reject(f);v.delete(k)}B(f,k,c){let e=A.get(f);e||(e=new Map,A.set(f,e));if(e.has(k))throw Error(`[DOM] Component '${f}' already has handler '${k}'`);e.set(k,c)}static Xb(f){if(w.includes(f))throw Error("DOM handler already added");w.push(f)}nd(){for(const f of this.Ib)if("runtime"===f.Ta){this.Ka=f;return}throw Error("cannot find runtime DOM handler");}sf(f){this.hc("debugger","message",
f)}Af(){for(const f of this.Ib)f.Xc()}static fc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ie(f){this.Ia.push(f);this.Bc()}Lf(f){f=this.Ia.indexOf(f);if(-1===f)throw Error("invalid callback");this.Ia.splice(f,1);this.Ia.length||this.nc()}Bc(){-1===this.Ja&&this.Ia.length&&(this.Ja=requestAnimationFrame(this.pg))}nc(){-1!==this.Ja&&(cancelAnimationFrame(this.Ja),this.Ja=-1)}wf(){this.Ja=-1;for(const f of this.Ia)f();this.Bc()}sa(f){this.Ka.sa(f)}Aa(f){this.Ka.Aa(f)}Ac(){this.Ka.Ac()}vb(f){this.Ka.vb(f)}te(){return!!d["audio/webm; codecs=opus"]}async ig(f){f=
await this.fd("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}se(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}ue(f){return!this.se(f)}async ef(f){const k=f.filename;switch(f.as){case "text":return await this.le(k);case "buffer":return await this.Zb(k);default:throw Error("unsupported type");}}$c(f){const k=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((c,e)=>{window.resolveLocalFileSystemURL(k,
l=>{l.file(c,e)},e)})}async le(f){f=await this.$c(f);return await g(f)}oc(){if(q.length&&!(8<=t)){t++;var f=q.shift();this.Oe(f.filename,f.yg,f.tg)}}Zb(f){return new Promise((k,c)=>{q.push({filename:f,yg:e=>{t--;this.oc();k(e)},tg:e=>{t--;this.oc();c(e)}});this.oc()})}async Oe(f,k,c){try{const e=await this.$c(f),l=await n(e);k(l)}catch(e){c(e)}}async Ne(){const f=[];for(const [k,c]of Object.entries(this.ha))f.push(this.Me(k,c));await Promise.all(f)}async Me(f,k){if("object"===typeof k)this.ha[f]=
new Blob([k.str],{type:k.type}),this.Nb[f]=k.str;else{let c=await this.Ve(k);c||(c=this.Qe(k));this.ha[f]=c}}async Ve(f){try{return await (await fetch(f)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Qe(f){f=this.Ff(f);return this.Le(f.data,f.vg)}Ff(f){var k=f.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");
var c=f.substring(k+1);k=f.substring(5,k).split(";");f=k[0]||"";const e=k[2];c="base64"===k[1]||"base64"===e?atob(c):decodeURIComponent(c);return{vg:f,data:c}}Le(f,k){var c=f.length;let e=c>>2,l=new Uint8Array(c),m=new Uint32Array(l.buffer,0,e),p,r;for(r=p=0;p<e;++p)m[p]=f.charCodeAt(r++)|f.charCodeAt(r++)<<8|f.charCodeAt(r++)<<16|f.charCodeAt(r++)<<24;for(c&=3;c--;)l[r]=f.charCodeAt(r),++r;return new Blob([l],{type:k})}}}"use strict";
{const h=self.tb;function a(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(c){return new Promise((e,l)=>{const m=document.createElement("link");m.onload=()=>e(m);m.onerror=p=>l(p);m.rel=
"stylesheet";m.href=c;document.head.appendChild(m)})}function t(c){return new Promise((e,l)=>{const m=new Image;m.onload=()=>e(m);m.onerror=p=>l(p);m.src=c})}async function w(c){c=URL.createObjectURL(c);try{return await t(c)}finally{URL.revokeObjectURL(c)}}function A(c){return new Promise((e,l)=>{let m=new FileReader;m.onload=p=>e(p.target.result);m.onerror=p=>l(p);m.readAsText(c)})}async function v(c,e,l){if(!/firefox/i.test(navigator.userAgent))return await w(c);var m=await A(c);m=(new DOMParser).parseFromString(m,
"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const r=p.getAttribute("width"),G=p.getAttribute("height");if(!r.includes("%")&&!G.includes("%"))return await w(c)}p.setAttribute("width",e+"px");p.setAttribute("height",l+"px");m=(new XMLSerializer).serializeToString(m);c=new Blob([m],{type:"image/svg+xml"});return await w(c)}function x(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const B=new Set(["canvas",
"body","html"]);function z(c){B.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function u(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await w(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const e=c.getBoundingClientRect();document.body.removeChild(c);return[e.width,e.height]}};self.C3_RasterSvgImageBlob=async function(c,
e,l,m,p){c=await v(c,e,l);const r=document.createElement("canvas");r.width=m;r.height=p;r.getContext("2d").drawImage(c,0,0,e,l);return r};let f=!1;document.addEventListener("pause",()=>f=!0);document.addEventListener("resume",()=>f=!1);function k(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}}h.Xb(class extends self.nb{constructor(c){super(c,"runtime");this.Hd=!0;this.La=-1;this.Tc="any";this.yd=this.zd=!1;this.Nc=this.ib=this.wa=null;c.B("canvas","update-size",m=>
this.Df(m));c.B("runtime","invoke-download",m=>this.qf(m));c.B("runtime","raster-svg-image",m=>this.xf(m));c.B("runtime","get-svg-image-size",m=>this.nf(m));c.B("runtime","set-target-orientation",m=>this.Bf(m));c.B("runtime","register-sw",()=>this.yf());c.B("runtime","post-to-debugger",m=>this.td(m));c.B("runtime","go-to-script",m=>this.td(m));c.B("runtime","before-start-ticking",()=>this.df());c.B("runtime","debug-highlight",m=>this.gf(m));c.B("runtime","enable-device-orientation",()=>this.Ke());
c.B("runtime","enable-device-motion",()=>this.Je());c.B("runtime","add-stylesheet",m=>this.bf(m));c.B("runtime","alert",m=>this.cf(m));c.B("runtime","hide-cordova-splash",()=>this.pf());const e=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;e.has(p.tagName.toLowerCase())||x(p)||m.preventDefault()});const l=c.I;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);l.addEventListener("selectstart",z);l.addEventListener("gesturehold",
z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),l.addEventListener("pointerdown",z)):l.addEventListener("touchstart",z);this.fb=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",u,{passive:!1});window.addEventListener("wheel",u,{passive:!1});window.addEventListener("resize",()=>this.Ef());c.rb()&&window.addEventListener("focusout",()=>{{const r=
document.activeElement;if(r){var m=r.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));m="textarea"===m?!0:"input"===m?p.has(r.type.toLowerCase()||"text"):x(r)}else m=!1}m||(document.scrollingElement.scrollTop=0)});this.Ga=new Set;this.Ob=new WeakSet;this.la=!1}df(){"cordova"===this.v.P?(document.addEventListener("pause",()=>this.zc(!0)),document.addEventListener("resume",()=>this.zc(!1))):document.addEventListener("visibilitychange",()=>this.zc(document.hidden));
return{isSuspended:!(!document.hidden&&!f)}}Xc(){window.addEventListener("focus",()=>this.Bb("window-focus"));window.addEventListener("blur",()=>{this.Bb("window-blur",{parentHasFocus:k()});this.fb=0});window.addEventListener("fullscreenchange",()=>this.vc());window.addEventListener("webkitfullscreenchange",()=>this.vc());window.addEventListener("mozfullscreenchange",()=>this.vc());window.addEventListener("fullscreenerror",e=>this.wc(e));window.addEventListener("webkitfullscreenerror",e=>this.wc(e));
window.addEventListener("mozfullscreenerror",e=>this.wc(e));window.addEventListener("keydown",e=>this.sd("keydown",e));window.addEventListener("keyup",e=>this.sd("keyup",e));window.addEventListener("dblclick",e=>this.xc("dblclick",e,d));window.addEventListener("wheel",e=>this.uf(e));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",e=>{this.rc(e);this.Ra("pointerdown",e)}),this.v.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ib=new self.ze(()=>this.Te(),
5),this.ib.Cd=!0,window.addEventListener("pointerrawupdate",e=>this.vf(e))):window.addEventListener("pointermove",e=>this.Ra("pointermove",e)),window.addEventListener("pointerup",e=>this.Ra("pointerup",e)),window.addEventListener("pointercancel",e=>this.Ra("pointercancel",e))):(window.addEventListener("mousedown",e=>{this.rc(e);this.yc("pointerdown",e)}),window.addEventListener("mousemove",e=>this.yc("pointermove",e)),window.addEventListener("mouseup",e=>this.yc("pointerup",e)),window.addEventListener("touchstart",
e=>{this.rc(e);this.zb("pointerdown",e)}),window.addEventListener("touchmove",e=>this.zb("pointermove",e)),window.addEventListener("touchend",e=>this.zb("pointerup",e)),window.addEventListener("touchcancel",e=>this.zb("pointercancel",e)));const c=()=>this.Ac();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}Bb(c,e){y(this,c,e||null,n)}ua(){return this.v.ua()}ta(){return this.v.ta()}Ef(){const c=
this.ua(),e=this.ta();this.Bb("window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio});this.v.rb()&&(-1!==this.La&&clearTimeout(this.La),this.ud(c,e,0))}Mf(c,e,l){-1!==this.La&&clearTimeout(this.La);this.La=setTimeout(()=>this.ud(c,e,l),48)}ud(c,e,l){const m=this.ua(),p=this.ta();this.La=-1;m!=c||p!=e?this.Bb("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>l&&this.Mf(m,p,l+1)}Bf(c){this.Tc=c.targetOrientation}eg(){const c=this.Tc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(c):screen.webkitLockOrientation?e=screen.webkitLockOrientation(c):screen.mozLockOrientation?e=screen.mozLockOrientation(c):screen.msLockOrientation&&(e=screen.msLockOrientation(c));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}vc(){const c=h.fc();c&&"any"!==this.Tc&&this.eg();y(this,"fullscreenchange",{isFullscreen:c,innerWidth:this.ua(),innerHeight:this.ta()})}wc(c){console.warn("[Construct 3] Fullscreen request failed: ",c);y(this,"fullscreenerror",{isFullscreen:h.fc(),innerWidth:this.ua(),innerHeight:this.ta()})}zc(c){c?this.v.nc():this.v.Bc();y(this,"visibilitychange",{hidden:c})}sd(c,e){"Backspace"===e.key&&z(e);const l=b.get(e.code)||e.code;C(this,c,{code:l,key:e.key,which:e.which,repeat:e.repeat,altKey:e.altKey,
ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,timeStamp:e.timeStamp},d)}uf(c){y(this,"wheel",{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},d)}xc(c,e,l){a(e)||C(this,c,{button:e.button,buttons:e.buttons,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,timeStamp:e.timeStamp},l)}yc(c,e){if(!a(e)){var l=this.fb;"pointerdown"===c&&0!==l?c="pointermove":"pointerup"===
c&&0!==e.buttons&&(c="pointermove");C(this,c,{pointerId:1,pointerType:"mouse",button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:e.timeStamp},d);this.fb=e.buttons;this.xc(e.type,e,g)}}Ra(c,e){if(this.ib&&"pointermove"!==c){var l=this.ib;l.Ya||(H(l),l.Lb=Date.now())}l=0;"mouse"===e.pointerType&&(l=this.fb);C(this,c,{pointerId:e.pointerId,pointerType:e.pointerType,
button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:e.width||0,height:e.height||0,pressure:e.pressure||0,tangentialPressure:e.tangentialPressure||0,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,timeStamp:e.timeStamp},d);"mouse"===e.pointerType&&(l="mousemove","pointerdown"===c?l="mousedown":"pointerup"===c&&(l="pointerup"),this.xc(l,e,g),this.fb=e.buttons)}vf(c){this.Nc=c;c=this.ib;if(-1===c.Ma){var e=Date.now(),l=e-c.Lb,m=c.kg;
l>=m&&c.Cd?(c.Lb=e,c.Ya=!0,c.Ec(),c.Ya=!1):c.Ma=self.setTimeout(c.Td,Math.max(m-l,4))}}Te(){this.Ra("pointermove",this.Nc);this.Nc=null}zb(c,e){for(let l=0,m=e.changedTouches.length;l<m;++l){const p=e.changedTouches[l];C(this,c,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:e.timeStamp},d)}}rc(c){window!==window.top&&window.focus();this.qd(c.target)&&document.activeElement&&!this.qd(document.activeElement)&&document.activeElement.blur()}qd(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}Ke(){this.zd||(this.zd=!0,window.addEventListener("deviceorientation",c=>this.jf(c)),window.addEventListener("deviceorientationabsolute",c=>this.kf(c)))}Je(){this.yd||(this.yd=!0,window.addEventListener("devicemotion",
c=>this.hf(c)))}jf(c){y(this,"deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},d)}kf(c){y(this,"deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},d)}hf(c){let e=null;var l=c.acceleration;l&&(e={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var m=c.accelerationIncludingGravity;m&&(l={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const p=c.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});y(this,"devicemotion",{acceleration:e,accelerationIncludingGravity:l,rotationRate:m,interval:c.interval,timeStamp:c.timeStamp},d)}Df(c){const e=this.v,l=e.I;l.style.width=c.styleWidth+"px";l.style.height=c.styleHeight+"px";l.style.marginLeft=c.marginLeft+"px";l.style.marginTop=c.marginTop+"px";e.ed();this.Hd&&(l.style.display="",this.Hd=!1)}qf(c){const e=c.url;c=c.filename;const l=document.createElement("a"),
m=document.body;l.textContent=c;l.href=e;l.download=c;m.appendChild(l);l.click();m.removeChild(l)}async xf(c){var e=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);e=e?await createImageBitmap(c,e):await createImageBitmap(c);return{imageBitmap:e,transferables:[e]}}async nf(c){return await self.C3_GetSvgImageSize(c.blob)}async bf(c){await q(c.url)}Ac(){var c=[...this.Ga];this.Ga.clear();if(!this.la)for(const e of c)(c=e.play())&&
c.catch(()=>{this.Ob.has(e)||this.Ga.add(e)})}sa(c){if("function"!==typeof c.play)throw Error("missing play function");this.Ob.delete(c);let e;try{e=c.play()}catch(l){this.Ga.add(c);return}e&&e.catch(()=>{this.Ob.has(c)||this.Ga.add(c)})}Aa(c){this.Ga.delete(c);this.Ob.add(c)}vb(c){this.la=!!c}pf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}gf(c){if(c.show){this.wa||(this.wa=document.createElement("div"),this.wa.id="inspectOutline",document.body.appendChild(this.wa));
var e=this.wa;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.wa&&(this.wa.style.display="none")}yf(){window.C3_RegisterSW&&window.C3_RegisterSW()}td(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}$e(c,e){return this.v.fd(this.Ta,"js-invoke-function",{name:c,params:e},void 0,void 0)}cf(c){alert(c.message)}})}"use strict";
async function J(h){if(h.jg)throw Error("already initialised");h.jg=!0;var a=h.Sb.qc("dispatchworker.js");h.Gc=await h.Sb.$b(a,h.J,{name:"DispatchWorker"});a=new MessageChannel;h.Kc=a.port1;h.Gc.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.Rc=await L(h)}function K(h){return[h.Kc,h.Rc]}
async function L(h){const a=h.Id.length;var b=h.Sb.qc("jobworker.js");b=await h.Sb.$b(b,h.J,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;h.Gc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);h.Id.push(b);return g.port1}
self.ve=class{constructor(h){this.Sb=h;this.J=h.J;this.J="preview"===h.P?this.J+"c3/workers/":this.J+h.Tb;this.mg=Math.min(navigator.hardwareConcurrency||2,16);this.Gc=null;this.Id=[];this.Rc=this.Kc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.tb({zg:!0,Ag:"workermain.js",Na:["scripts/c3runtime.js"],wg:"scripts/",Wc:[],Ud:"html5"}));"use strict";
self.tb.Xb(class extends self.nb{constructor(h){super(h,"mouse");D(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const h=180/Math.PI;self.da=class extends self.nb{constructor(a){super(a,"audio");this.Hb=this.f=null;this.Jb=this.Jc=!1;this.oa=()=>this.fg();this.aa=[];this.C=[];this.ga=null;this.Jd="";this.Kd=-1;this.hb=new Map;this.Oc=1;this.la=!1;this.Uc=0;this.Vb=1;this.Hc=0;this.Md="HRTF";this.Dd="inverse";this.Nd=600;this.Ld=1E4;this.Pd=1;this.Fd=this.Sc=!1;this.qg=this.v.te();this.ba=new Map;this.Da=new Set;this.Lc=!1;this.Pc="";this.xa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.tf(b,d);this.Gb=null;
self.C3Audio_GetOutputStream=()=>this.mf();self.C3Audio_DOMInterface=this;E(this,[["create-audio-context",b=>this.Pe(b)],["play",b=>this.Gf(b)],["stop",b=>this.cg(b)],["stop-all",()=>this.dg()],["set-paused",b=>this.Wf(b)],["set-volume",b=>this.ag(b)],["fade-volume",b=>this.Ue(b)],["set-master-volume",b=>this.Uf(b)],["set-muted",b=>this.Vf(b)],["set-silent",b=>this.Yf(b)],["set-looping",b=>this.Tf(b)],["set-playback-rate",b=>this.Xf(b)],["seek",b=>this.Nf(b)],["preload",b=>this.Hf(b)],["unload",b=>
this.gg(b)],["unload-all",()=>this.hg()],["set-suspended",b=>this.Zf(b)],["add-effect",b=>this.ld(b)],["set-effect-param",b=>this.Qf(b)],["remove-effects",b=>this.Jf(b)],["tick",b=>this.Cf(b)],["load-state",b=>this.rf(b)]])}async Pe(a){a.isiOSCordova&&(this.Sc=!0);this.Uc=a.timeScaleMode;this.Md=["equalpower","HRTF","soundfield"][a.panningModel];this.Dd=["linear","inverse","exponential"][a.distanceModel];this.Nd=a.refDistance;this.Ld=a.maxDistance;this.Pd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.md();this.f.onstatechange=()=>{"running"!==this.f.state&&this.md()};this.Hb=this.f.createGain();this.Hb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.ac();try{await Promise.all(a.preloadList.map(d=>
this.xb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}md(){this.Jb||(this.Jc=!1,window.addEventListener("pointerup",this.oa,!0),window.addEventListener("touchend",this.oa,!0),window.addEventListener("click",this.oa,!0),window.addEventListener("keydown",this.oa,!0),this.Jb=!0)}Re(){this.Jb&&(this.Jc=!0,window.removeEventListener("pointerup",this.oa,!0),window.removeEventListener("touchend",this.oa,!0),window.removeEventListener("click",
this.oa,!0),window.removeEventListener("keydown",this.oa,!0),this.Jb=!1)}fg(){if(!this.Jc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Re()}}W(){return this.f}ac(){return this.f.currentTime}qa(){return this.Hb}bd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].O():this.qa()}Wd(a,b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.Sf(d.length);
b.$f(a);d.push(b);this.wd(a)}wd(a){let b=this.qa();const d=this.ba.get(a);if(d&&d.length){b=d[0].O();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.qa()):q.S(d[g+1].O())}}for(const g of this.ja(a))g.Ae(b);this.xa&&this.Pc===a&&(this.xa.disconnect(),this.xa.connect(b))}pb(){return this.Oc}qb(){return this.la}Rf(){this.Fd=!0}ne(a,b){return b?this.v.ig(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.f.decodeAudioData(a,
d,g)})}sa(a){this.v.sa(a)}Aa(a){this.v.Aa(a)}gd(a){let b=0;for(let d=0,g=this.C.length;d<g;++d){const n=this.C[d];this.C[b]=n;n.K===a?n.c():++b}this.C.length=b}Be(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.ra()?g.c():++a}this.aa.length=a}*ja(a){if(a)for(const b of this.C)self.da.oe(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async xb(a,b,d,g,n){for(const q of this.aa)if(q.Pa()===b)return await M(q),q;if(n)return null;g&&(this.Sc||this.Fd)&&
this.Be();n="audio/webm; codecs=opus"===d&&!this.qg;g&&n&&this.Rf();a=!g||this.Sc||n?new self.je(this,a,b,d,g,n):new self.he(this,a,b,d,g);this.aa.push(a);await M(a);return a}async pc(a,b,d,g,n){for(const q of this.C)if(q.Pa()===b&&(q.Yb()||n))return q.De(g),q;a=await this.xb(a,b,d,n);g="html5"===a.Cc?new self.ie(a.i,a,g):new self.ke(a.i,a,g);this.C.push(g);return g}He(a){let b=this.hb.get(a);if(!b){let d=null;b={Vc:0,promise:new Promise(g=>d=g),resolve:d};this.hb.set(a,b)}b.Vc++}Kf(a){const b=this.hb.get(a);
if(!b)throw Error("expected pending tag");b.Vc--;0===b.Vc&&(b.resolve(),this.hb.delete(a))}mc(a){a||(a=this.Jd);return(a=this.hb.get(a))?a.promise:Promise.resolve()}yb(){if(0<this.Da.size)F(this);else for(const a of this.C)if(a.cd()){F(this);break}}Ba(){for(var a of this.Da)a.Ba();a=this.ac();for(var b of this.C)b.Ba(a);b=this.C.filter(d=>d.cd()).map(d=>d.Oa());y(this,"state",{tickCount:this.Kd,audioInstances:b,analysers:[...this.Da].map(d=>d.qe())});0===b.length&&0===this.Da.size&&this.Kb&&(this.v.Lf(this.Sd),
this.Kb=!1)}ic(a,b,d){y(this,"trigger",{type:a,tag:b,aiid:d})}async Gf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,t=a.isLooping,w=a.vol,A=a.pos,v=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Jd=q;this.He(q);try{this.ga=await this.pc(b,d,g,q,n),v?(this.ga.ub(!0),this.ga.Ce(v.x,v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&
this.ga.Ee(v.uid)):this.ga.ub(!1),this.ga.Play(t,w,A,x)}catch(B){console.error("[Construct 3] Audio: error starting playback: ",B);return}finally{this.Kf(q)}F(this)}cg(a){a=a.tag;for(const b of this.ja(a))b.ka()}dg(){for(const a of this.C)a.ka()}Wf(a){const b=a.tag;a=a.paused;for(const d of this.ja(b))a?d.Qa():d.sb();this.yb()}ag(a){const b=a.tag;a=a.vol;for(const d of this.ja(b))d.wb(a)}async Ue(a){const b=a.tag,d=a.vol,g=a.duration;a=a.stopOnEnd;await this.mc(b);for(const n of this.ja(b))n.pe(d,
g,a);this.yb()}Uf(a){this.Oc=a.vol;for(const b of this.C)b.Eb()}Vf(a){const b=a.tag;a=a.isMuted;for(const d of this.ja(b))d.hd(a)}Yf(a){this.la=a.isSilent;this.v.vb(this.la);for(const b of this.C)b.Db()}Tf(a){const b=a.tag;a=a.isLooping;for(const d of this.ja(b))d.kc(a)}async Xf(a){const b=a.tag;a=a.rate;await this.mc(b);for(const d of this.ja(b))d.kd(a)}async Nf(a){const b=a.tag;a=a.pos;await this.mc(b);for(const d of this.ja(b))d.jc(a)}async Hf(a){const b=a.originalUrl,d=a.url,g=a.type;a=a.isMusic;
try{await this.pc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async gg(a){if(a=await this.xb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}hg(){for(const a of this.aa)a.c();this.aa.length=0}Zf(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.lc(a);a&&this.f.suspend&&this.f.suspend()}Cf(a){this.Vb=a.timeScale;this.Hc=a.gameTime;this.Kd=a.tickCount;if(0!==this.Uc)for(var b of this.C)b.Ca();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.C)g.fa===a&&g.jd(d.x,d.y,d.angle)}}async ld(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.be(this,...g);else if("delay"===b)g=new self.$d(this,...g);else if("convolution"===b){b=null;try{b=await this.xb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}g=new self.Zd(this,b.$,...g);g.Of(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.ce(this,...g);else if("phaser"===b)g=new self.ee(this,...g);else if("gain"===b)g=new self.de(this,...g);else if("tremolo"===b)g=new self.ge(this,...g);else if("ringmod"===b)g=new self.fe(this,...g);else if("distortion"===b)g=new self.ae(this,...g);else if("compressor"===b)g=new self.Yd(this,...g);else if("analyser"===b)g=new self.Xd(this,...g);else throw Error("invalid effect type");this.Wd(d,g);this.vd()}Qf(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,
q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.vd())}Jf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.wd(a)}}Ge(a){this.Da.add(a);this.yb()}If(a){this.Da.delete(a)}vd(){this.Lc||(this.Lc=!0,Promise.resolve().then(()=>this.Se()))}Se(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Oa());y(this,"fxstate",{fxstate:a});this.Lc=!1}async rf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.C)d.ra()&&1===
b||(d.ra()||2!==b)&&d.ka();for(const g of this.ba.values())for(const n of g)n.c();this.ba.clear();this.Vb=a.timeScale;this.Hc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.la=a.isSilent;this.v.vb(this.la);this.Oc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.ld(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.af(g,b)));this.yb()}async af(a,b){if(3!==b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,
q=a.isMusic,t=a.tag,w=a.isLooping,A=a.volume,v=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.pc(d,g,n,t,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.ye(a.pan);b.Play(w,A,v,0);a.isPlaying||b.Qa();b.tc(a)}}}tf(a,b){this.xa&&this.xa.disconnect();this.Pc=b.toLowerCase();this.xa=this.f.createMediaStreamSource(a);this.xa.connect(this.bd(this.Pc))}mf(){this.Gb||(this.Gb=this.f.createMediaStreamDestination(),this.Hb.connect(this.Gb));return this.Gb.stream}static oe(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Fe(a){return a*h}static me(a){return Math.pow(10,a/20)}static ad(a){return Math.max(Math.min(self.da.me(a),1),0)}static xe(a){return Math.log(a)/Math.log(10)*20}static we(a){return self.da.xe(Math.max(Math.min(a,1),0))}static sg(a,b){return 1-Math.exp(-b*a)}};self.tb.Xb(self.da)}"use strict";function M(h){h.Mb||(h.Mb=h.sc());return h.Mb}
self.Yc=class{constructor(h,a,b,d,g){this.i=h;this.og=a;this.ya=b;this.R=d;this.lg=g;this.Cc="";this.Mb=null}c(){this.Mb=this.i=null}sc(){}W(){return this.i.W()}cc(){return this.og}Pa(){return this.ya}bc(){return this.R}ra(){return this.lg}ea(){}};"use strict";
self.he=class extends self.Yc{constructor(h,a,b,d,g){super(h,a,b,d,g);this.Cc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.ab=this.bb=null;this.H.addEventListener("canplaythrough",()=>!0);this.gb=this.W().createGain();this.eb=null;this.H.addEventListener("canplay",()=>{this.bb&&(this.bb(),this.ab=this.bb=null);!this.eb&&this.H&&(this.eb=this.W().createMediaElementSource(this.H),this.eb.connect(this.gb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.ya}' error: `,n);this.ab&&(this.ab(n),this.ab=this.bb=null)})}c(){this.i.gd(this);this.gb.disconnect();this.gb=null;this.eb.disconnect();this.eb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}sc(){return new Promise((h,a)=>{this.bb=h;this.ab=a;this.H.src=this.ya})}N(){return this.H}ea(){return this.H.duration}};"use strict";
async function N(h){if(h.va)return h.va;var a=h.i.v;if("cordova"===a.P&&a.ue(h.ya)&&"file:"===location.protocol)h.va=await a.Zb(h.ya);else{a=await fetch(h.ya);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.va=await a.arrayBuffer()}}async function O(h){if(h.$)return h.$;h.$=await h.i.ne(h.va,h.ng);h.va=null}
self.je=class extends self.Yc{constructor(h,a,b,d,g,n){super(h,a,b,d,g);this.Cc="webaudio";this.$=this.va=null;this.ng=!!n}c(){this.i.gd(this);this.$=this.va=null;super.c()}async sc(){try{await N(this),await O(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.ya}': `,h)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let h=0;self.Zc=class{constructor(a,b,d){this.i=a;this.K=b;this.Z=d;this.Fb=h++;this.L=this.W().createGain();this.L.connect(this.qa());this.A=null;this.Za=!1;this.F=!0;this.V=this.ia=this.D=!1;this.kb=1;this.Ea=!1;this.Y=1;a=this.i.Uc;this.Mc=1===a&&!this.ra()||2===a;this.Wa=this.fa=-1;this.Rd=!1}c(){this.K=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.L.disconnect();this.L=null}W(){return this.i.W()}qa(){return this.i.bd(this.Z)}pb(){return this.i.pb()}ob(){return this.Mc?this.i.Hc:
performance.now()/1E3}cc(){return this.K.cc()}Pa(){return this.K.Pa()}bc(){return this.K.bc()}ra(){return this.K.ra()}De(a){this.Z=a}T(){}Yb(){}IsPlaying(){return!this.F&&!this.D&&!this.T()}cd(){return!this.F&&!this.T()}za(){}ea(){return this.K.ea()}Play(){}ka(){}Qa(){}sb(){}wb(a){this.kb=a;this.L.gain.cancelScheduledValues(0);this.Wa=-1;this.L.gain.value=this.dc()}pe(a,b,d){if(!this.Ea){a*=this.pb();var g=this.L.gain;g.cancelScheduledValues(0);var n=this.i.ac();b=n+b;g.setValueAtTime(g.value,n);
g.linearRampToValueAtTime(a,b);this.kb=a;this.Wa=b;this.Rd=d}}Eb(){this.wb(this.kb)}Ba(a){-1!==this.Wa&&a>=this.Wa&&(this.Wa=-1,this.Rd&&this.ka(),this.i.ic("fade-ended",this.Z,this.Fb))}dc(){const a=this.kb*this.pb();return isFinite(a)?a:0}hd(a){a=!!a;this.Ea!==a&&(this.Ea=a,this.Db())}qb(){return this.i.qb()}Db(){}kc(){}kd(a){this.Y!==a&&(this.Y=a,this.Ca())}Ca(){}jc(){}lc(){}ub(a){a=!!a;this.Za!==a&&((this.Za=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Md,this.A.distanceModel=
this.i.Dd,this.A.refDistance=this.i.Nd,this.A.maxDistance=this.i.Ld,this.A.rolloffFactor=this.i.Pd),this.L.disconnect(),this.L.connect(this.A),this.A.connect(this.qa())):(this.A.disconnect(),this.L.disconnect(),this.L.connect(this.qa())))}Ce(a,b,d,g,n,q){this.Za&&(this.jd(a,b,d),a=self.da.Fe,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(n),this.A.coneOuterGain=q)}jd(a,b,d){this.Za&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(d),Math.sin(d),0))}Ee(a){this.fa=a}ec(){}Ae(a){const b=
this.A||this.L;b.disconnect();b.connect(a)}Oa(){return{aiid:this.Fb,tag:this.Z,duration:this.ea(),volume:this.kb,isPlaying:this.IsPlaying(),playbackTime:this.za(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.cc(),bufferUrl:"",bufferType:this.bc(),isMusic:this.ra(),isLooping:this.V,isMuted:this.Ea,resumePosition:this.ec(),pan:this.re()}}tc(a){this.kd(a.playbackRate);this.hd(a.isMuted)}re(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}ye(a){a?(this.ub(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.ub(!1)}}}"use strict";
self.ie=class extends self.Zc{constructor(h,a,b){super(h,a,b);this.K.gb.connect(this.L);this.K.onended=()=>this.uc()}c(){this.ka();this.K.gb.disconnect();super.c()}N(){return this.K.N()}uc(){this.F=!0;this.fa=-1;this.i.ic("ended",this.Z,this.Fb)}T(){return this.N().ended}Yb(){return this.F?!0:this.T()}za(h){let a=this.N().currentTime;h&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(h,a,b){const d=this.N();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==h&&(d.loop=h);this.wb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.K.Pa()}' to position '${b}': `,g)}this.i.sa(d);this.D=this.F=!1;this.V=h;this.Y=1}ka(){const h=this.N();h.paused||h.pause();this.i.Aa(h);this.F=!0;this.D=!1;this.fa=-1}Qa(){if(!(this.D||this.F||this.T())){var h=this.N();h.paused||h.pause();this.i.Aa(h);this.D=!0}}sb(){!this.D||this.F||this.T()||(this.i.sa(this.N()),this.D=!1)}Db(){this.N().muted=this.Ea||this.qb()}kc(h){h=!!h;
this.V!==h&&(this.V=h,this.N().loop=h)}Ca(){let h=this.Y;this.Mc&&(h*=this.i.Vb);try{this.N().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}jc(h){if(!this.F&&!this.T())try{this.N().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}ec(){return this.za()}lc(h){h?this.IsPlaying()?(this.N().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.sa(this.N()),this.ia=!1)}};"use strict";
function P(h){h.j&&h.j.disconnect();h.j=null;h.Sa=null}
self.ke=class extends self.Zc{constructor(h,a,b){super(h,a,b);this.j=null;this.Pb=d=>this.uc(d);this.Ic=!0;this.Sa=null;this.M=this.Ub=0;this.Qc=1}c(){this.ka();P(this);this.Pb=null;super.c()}uc(h){this.D||this.ia||h.target!==this.Sa||(this.F=this.Ic=!0,this.fa=-1,P(this),this.i.ic("ended",this.Z,this.Fb))}T(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Ic}Yb(){return!this.j||this.F?!0:this.T()}za(h){let a;a=this.D?this.M:this.ob()-this.Ub;h&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(h,
a,b,d){this.Qc=1;this.wb(a);P(this);this.j=this.W().createBufferSource();this.j.buffer=this.K.$;this.j.connect(this.L);this.Sa=this.j;this.j.onended=this.Pb;this.j.loop=h;this.j.start(d,b);this.D=this.F=this.Ic=!1;this.V=h;this.Y=1;this.Ub=this.ob()-b}ka(){if(this.j)try{this.j.stop(0)}catch(h){}this.F=!0;this.D=!1;this.fa=-1}Qa(){this.D||this.F||this.T()||(this.M=this.za(!0),this.V&&(this.M%=this.ea()),this.D=!0,this.j.stop(0))}sb(){!this.D||this.F||this.T()||(P(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.K.$,this.j.connect(this.L),this.Sa=this.j,this.j.onended=this.Pb,this.j.loop=this.V,this.Eb(),this.Ca(),this.Ub=this.ob()-this.M/(this.Y||.001),this.j.start(0,this.M),this.D=!1)}dc(){return super.dc()*this.Qc}Db(){this.Qc=this.Ea||this.qb()?0:1;this.Eb()}kc(h){h=!!h;this.V!==h&&(this.V=h,this.j&&(this.j.loop=h))}Ca(){let h=this.Y;this.Mc&&(h*=this.i.Vb);this.j&&(this.j.playbackRate.value=h)}jc(h){this.F||this.T()||(this.D?this.M=h:(this.Qa(),this.M=h,this.sb()))}ec(){return this.M}lc(h){h?
this.IsPlaying()?(this.ia=!0,this.M=this.za(!0),this.V&&(this.M%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(P(this),this.j=this.W().createBufferSource(),this.j.buffer=this.K.$,this.j.connect(this.L),this.Sa=this.j,this.j.onended=this.Pb,this.j.loop=this.V,this.Eb(),this.Ca(),this.Ub=this.ob()-this.M/(this.Y||.001),this.j.start(0,this.M),this.ia=!1)}tc(h){super.tc(h);this.M=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.f=a.W();this.Gd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}Sf(a){this.Gd=a}$f(a){this.Z=a}o(){return this.f.createGain()}O(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Oa(){return{type:this.R,tag:this.Z,params:this.g}}}
self.be=class extends h{constructor(a,b,d,g,n,q,t){super(a);this.R="filter";this.g=[b,d,g,n,q,t];this.l=this.o();this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.$d=class extends h{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.cb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Va=this.o();this.Va.gain.value=d;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b);this.cb.connect(this.U);this.U.connect(this.Va);this.Va.connect(this.cb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.cb.disconnect();this.U.disconnect();this.Va.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){const n=self.da.ad;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.Va.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.Zd=class extends h{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Bd=this.Ad="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Ua=this.f.createConvolver();this.Ua.normalize=d;this.Ua.buffer=b;this.l.connect(this.Ua);this.l.connect(this.a);this.Ua.connect(this.b)}c(){this.l.disconnect();this.Ua.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Of(a,b){this.Ad=a;this.Bd=b}Oa(){const a=
super.Oa();a.bufferOriginalUrl=this.Ad;a.bufferUrl="";a.bufferType=this.Bd;return a}};self.ce=class extends h{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.Xa=this.o();this.Xa.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.G=this.o();this.G.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.Xa);this.Xa.connect(this.U);this.s.connect(this.G);this.G.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Xa.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.Xa.gain,b/100,d,g)}}};self.ee=class extends h{constructor(a,b,d,g,n,q,t){super(a);this.R="phaser";this.g=[b,d,g,n,q,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=q;this.G=this.o();this.G.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.G.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.de=class extends h{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,g){const n=self.da.ad;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.ge=class extends h{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=d/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,d,g);this.m(this.G.gain.value,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.fe=class extends h{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.jb=this.o();
this.jb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.jb.gain);this.s.start(0);this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.jb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,d,g);this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ae=class extends h{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.Rb=this.o();this.Qb=this.o();this.Pf(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.Wb=this.f.createWaveShaper();this.Fc=new Float32Array(65536);this.We(b,d);this.Wb.curve=this.Fc;this.l.connect(this.Rb);this.l.connect(this.a);this.Rb.connect(this.Wb);
this.Wb.connect(this.Qb);this.Qb.connect(this.b)}c(){this.l.disconnect();this.Rb.disconnect();this.Wb.disconnect();this.Qb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Pf(a,b){.01>a&&(a=.01);this.Rb.gain.value=a;this.Qb.gain.value=Math.pow(1/a,.6)*b}We(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.bg(g,a,b);this.Fc[32768+d]=g;this.Fc[32768-d-1]=-g}}bg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.sg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.Yd=class extends h{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.Xd=class extends h{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Ed=new Float32Array(this.h.frequencyBinCount);this.Qd=new Uint8Array(b);this.Od=this.Ha=0;this.i.Ge(this)}c(){this.i.If(this);this.h.disconnect();super.c()}Ba(){this.h.getFloatFrequencyData(this.Ed);this.h.getByteTimeDomainData(this.Qd);const a=this.h.fftSize;let b=this.Ha=0;for(var d=0;d<a;++d){let g=(this.Qd[d]-128)/128;0>g&&(g=-g);
this.Ha<g&&(this.Ha=g);b+=g*g}d=self.da.we;this.Ha=d(this.Ha);this.Od=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}qe(){return{tag:this.Z,index:this.Gd,peak:this.Ha,rms:this.Od,binCount:this.h.frequencyBinCount,freqBins:this.Ed}}}};